### PR TITLE
Fix errors in didjvu bundle flow.

### PR DESCRIPTION
**Pull request by rmast**

### CODE REVIEW

**Comment by FriedrichFroebel** [comment]
Thanks for the PR. Do you mind adding a basic test case for this if possible, as this does not seem to be covered at the moment (otherwise it should have failed beforehand)?

**Comment by rmast** [comment]
I'll look up how to do that. Never did it before for this language, but it would be a good experience.

**Comment by FriedrichFroebel** [comment]
By the way: Declaring

```
_djvu_header = b'AT&TFORM\0\0\0\0DJVMDIRM\0\0\0\0\1'
```

as bytes directly and using

```
bzz.stdin.write(b'\0')
```

could make the code shorter as we do not have to do the `encode()` manually.

**Comment by rmast** [comment]
Good suggestions!
I've done an attempt to write a test based on another test, but that test only tests the argument-parser and doesn't really execute didjvu. There is no overall-test that just executes didjvu and inspects the results for any of the three flows, so building a test for a subflow will involve building a complete new test.

The way to reproduce the error you want on the unpatched code is:

./didjvu bundle eggs.png eggs.png --pages-per-dict=2

**Comment by FriedrichFroebel** [comment]
I have looked into this now and found a way to test the method in an isolated manner to check the issue from this PR does not occur any more. To keep it simple I mocked away the subprocess calls involved (as I do not want to research the required files for this). A full `didjvu bundle` integration test could be added later, but for now this simple unit test should be enough.

The fix has been committed manually as 0d74c0b060ab3c16e67c043b00c6134cd9d8e7ce to directly include the test as well as the code simplifications mentioned above. Thanks for reporting again.

**Pull request closed without merging**
